/*****************************************
시퀀스 삭제
******************************************/
DROP SEQUENCE RENT_NO_SEQ;
DROP SEQUENCE LONGRENT_NO_SEQ;
DROP SEQUENCE EVENT_CODE_SEQ;
DROP SEQUENCE EVENT_BOX_SEQ;
DROP SEQUENCE OPT_BOX_SEQ;

/*****************************************
시퀀스 생성
******************************************/

--RENT(no)
CREATE SEQUENCE RENT_NO_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRI_RENT_NO_SEQ
BEFORE INSERT ON RENT
FOR EACH ROW
BEGIN
	IF Inserting AND :NEW.RENT_NO IS NULL THEN 
		SELECT RENT_NO_SEQ.NEXTVAL INTO :NEW.RENT_NO FROM DUAL;
	END IF;
END;

-- OPT_BOX
CREATE SEQUENCE OPT_BOX_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRI_OPT_BOX_SEQ
BEFORE INSERT ON OPT_BOX
FOR EACH ROW
BEGIN
	IF Inserting AND :NEW.OPT_BOX IS NULL THEN 
		SELECT OPT_BOX_SEQ.NEXTVAL INTO :NEW.OPT_BOX FROM DUAL;
	END IF;
END;

--LONGRENT(no)
CREATE SEQUENCE LONGRENT_NO_SEQ
	START WITH 1
	INCREMENT BY 1;
	
CREATE OR REPLACE TRIGGER TRI_LONGRENT_NO_SEQ
BEFORE INSERT ON LONGRENT
FOR EACH ROW
BEGIN
	IF Inserting AND :NEW.NO IS NULL THEN
		SELECT LONGRENT_NO_SEQ.NEXTVAL INTO :NEW.NO FROM DUAL;
	END IF;
END;

-- EVENT (code)
CREATE SEQUENCE EVENT_CODE_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER EVENT_CODE_SEQ
BEFORE INSERT ON EVENT
FOR EACH ROW
BEGIN
	IF Inserting AND :NEW.EVENT_CODE IS NULL THEN 
		SELECT EVENT_CODE_SEQ.NEXTVAL INTO :NEW.EVENT_CODE FROM DUAL;
	END IF;
END;

-- EVENT_BOX (box)
CREATE SEQUENCE EVENT_BOX_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER EVENT_BOX_SEQ
BEFORE INSERT ON EVENT_BOX
FOR EACH ROW
BEGIN
	IF Inserting AND :NEW.EVENT_BOX IS NULL THEN 
		SELECT EVENT_BOX_SEQ.NEXTVAL INTO :NEW.EVENT_BOX FROM DUAL;
	END IF;
END;