SELECT * FROM CAR;
SELECT * FROM MEMBER;
SELECT * FROM ADMIN;
SELECT * FROM RENT;
SELECT * FROM INSURANCE;
SELECT * FROM LONGRENT;
SELECT * FROM OPTIONS;
SELECT * FROM KIND;
SELECT * FROM EVENT;
SELECT * FROM BRAND;
SELECT * FROM EVENT_BOX;
SELECT * FROM OPT_BOX;
--조회----------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT *  FROM car c LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE 
WHERE CAR_NO NOT IN (SELECT DISTINCT CAR_NO
FROM rent r
WHERE NOT(TO_DATE(RENT_DATE) > TO_DATE('202010090','YYYYMMDDHH24') OR TO_DATE(RETURN_DATE) < TO_DATE('202010090','YYYYMMDDHH24')));


INSERT INTO LONGRENT(NO, TITLE, CONTENTS,RENT_TERM, NAME, TEL, PWD, OPTIONS) VALUES(LONGRENT_NO_SEQ.NEXTVAL,?,?,empty_clob(),?,?,?,?);

INSERT INTO LONGRENT(NO, TITLE, CONTENTS, REP_YN, WRITE_DATE, RENT_TERM, NAME, TEL, PWD, OPTIONS)
VALUES(LONGRENT_NO_SEQ.NEXTVAL, 'K3TheNew 1년 장기렌트',empty_clob(), 1, SYSDATE,'365일','김창동','010-1234-1111','1111','옵션없음');

SELECT EVENT_CODE, NAME, SALE, THUM_IMAGE, VIEW_IMAGE, IS_EVENT FROM EVENT ORDER BY TO_NUMBER(EVENT_CODE) DESC;

SELECT * FROM car c LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE LEFT OUTER JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE;


SELECT * FROM CAR c LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE
 WHERE CAR_NO NOT IN (SELECT DISTINCT CAR_NO FROM rent r
 WHERE (TO_DATE(RENT_DATE) > TO_DATE('2020101000','YYYYMMDDHH24') AND TO_DATE(RENT_DATE) < TO_DATE('2020051000','YYYYMMDDHH24')) 
	OR (TO_DATE(RETURN_DATE) > TO_DATE('2020051009','YYYYMMDDHH24') AND TO_DATE(RETURN_DATE) < TO_DATE('2020101509','YYYYMMDDHH24')));
	
SELECT EVENT_CODE, NAME, SALE, THUM_IMAGE, VIEW_IMAGE, IS_EVENT FROM EVENT ORDER BY TO_NUMBER(EVENT_CODE) DESC;

SELECT EVENT_BOX, EVENT_CODE, ID, IS_EVENT FROM EVENT_BOX WHERE EVENT_CODE = 1 AND ID = 'dong';

SELECT * FROM EVENT;
SELECT * FROM EVENT_BOX;

-- 한 회원에 대한 할인쿠폰 조회
SELECT E.NAME, E.SALE
FROM EVENT_BOX B, EVENT E
WHERE B.IS_EVENT = 'n' AND B.ID = 'dong' AND B.EVENT_CODE = E.EVENT_CODE;

