SELECT * FROM CAR;
SELECT * FROM MEMBER;
SELECT * FROM ADMIN;
SELECT * FROM RENT;
SELECT * FROM INSURANCE;
SELECT * FROM LONGRENT;
SELECT * FROM OPTIONS;
SELECT * FROM KIND;
SELECT * FROM EVENT;
SELECT * FROM BRAND;
SELECT * FROM EVENT_BOX;
SELECT * FROM OPT_BOX;
--조회----------------------------------------------------------------------------------------------------------------------------------------------------------

-- 한 회원에 대한 할인쿠폰 조회
SELECT E.NAME, E.SALE
FROM EVENT_BOX B, EVENT E
WHERE B.IS_EVENT = 'n' AND B.ID = 'dong' AND B.EVENT_CODE = E.EVENT_CODE;


SELECT E.NAME, E.SALE FROM EVENT_BOX B, EVENT E WHERE B.IS_EVENT = 'n' AND B.ID = 'dong' AND B.EVENT_CODE = E.EVENT_CODE;
SELECT * FROM CAR WHERE CAR_NO = '11하0123';

INSERT INTO RENT(ID, CAR_NO, INS_CODE, RENT_DATE, RETURN_DATE, IS_RENT, RENT_FARE, RENT_REMARK) 
values('dong', '11하0123', 1, to_date('2020-10-30','YYYY-MM-DD HH24:MI:SS'), 
to_date('2020-10-27','YYYY-MM-DD HH24:MI:SS'), 'y', 80000, '동동 렌트 테스트');

SELECT * FROM KIND;

SELECT * FROM INSURANCE
ORDER BY INS_CODE;

SELECT * FROM OPTIONS;
SELECT * FROM OPTIONS ORDER BY OPT_CODE;

SELECT min(return_date) FROM RENT WHERE CAR_NO = '11하0123';

-- 단기렌트 조회
SELECT * FROM Rent r LEFT OUTER JOIN MEMBER m ON r.ID = m.ID JOIN INSURANCE i ON r.INS_CODE = i.INS_CODE
JOIN car c ON r.CAR_NO = c.CAR_NO LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE;

-- 단기렌트 조회 + 검색
SELECT * FROM Rent r LEFT OUTER JOIN MEMBER m ON r.ID = m.ID JOIN INSURANCE i ON r.INS_CODE = i.INS_CODE
JOIN car c ON r.CAR_NO = c.CAR_NO LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE
WHERE c.car_name LIKE '%모%';

-- 페이징용 카운팅
SELECT count(*) FROM Rent r LEFT OUTER JOIN MEMBER m ON r.ID = m.ID JOIN INSURANCE i ON r.INS_CODE = i.INS_CODE
JOIN car c ON r.CAR_NO = c.CAR_NO LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE;

-- 페이징
SELECT * FROM (SELECT rownum RN, a.* FROM (SELECT * FROM Rent r LEFT OUTER JOIN MEMBER m ON r.ID = m.ID JOIN INSURANCE i ON r.INS_CODE = i.INS_CODE
	JOIN car c ON r.CAR_NO = c.CAR_NO LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE) a) WHERE RN BETWEEN 1 AND 10 ORDER BY RN;
				
-- 검색 + 페이징
SELECT * FROM (SELECT rownum RN, a.* FROM (SELECT * FROM Rent r LEFT OUTER JOIN MEMBER m ON r.ID = m.ID JOIN INSURANCE i ON r.INS_CODE = i.INS_CODE
JOIN car c ON r.CAR_NO = c.CAR_NO LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE WHERE C.CAR_NO LIKE '%11%') a) WHERE RN BETWEEN 1 AND 5
ORDER BY RN;

-- WHERE R.ID LIKE '%kim%') a) WHERE RN BETWEEN 1 AND 5


SELECT * FROM (SELECT rownum RN, a.* FROM (SELECT * FROM Rent r LEFT OUTER JOIN MEMBER m ON r.ID = m.ID JOIN INSURANCE i ON r.INS_CODE = i.INS_CODE  
				JOIN car c ON r.CAR_NO = c.CAR_NO LEFT OUTER join kind k ON c.KIND_CODE = k.KIND_CODE JOIN BRAND b ON c.BRAND_CODE = b.BRAND_CODE) a) WHERE RN BETWEEN 1 AND 13 ORDER BY RN;
				
SELECT * FROM OPT_BOX;
SELECT * FROM RENT;

-- 가장 최근에 INSERT한 값 조회
SELECT MAX(RENT_NO) AS RENT_NO FROM rent
WHERE RENT_DATE = (SELECT MAX(RENT_DATE) FROM RENT);

SELECT MAX(RENT_NO) AS RENT_NO FROM rent WHERE RENT_DATE = (SELECT MAX(RENT_DATE) FROM RENT);

SELECT MAX(RENT_NO) AS RENT_NO FROM RENT
ORDER BY RENT_NO DESC;

SELECT MAX(RENT_NO) AS RENT_NO FROM RENT ORDER BY RENT_NO DESC;
