SELECT * FROM CAR;
SELECT * FROM MEMBER;
SELECT * FROM ADMIN;
SELECT * FROM RENT;
SELECT * FROM INSURANCE;
SELECT * FROM LONGRENT;
SELECT * FROM OPTIONS;
SELECT * FROM KIND;
SELECT * FROM EVENT;
SELECT * FROM BRAND;
SELECT * FROM EVENT_BOX;
SELECT * FROM OPT_BOX;
--조회----------------------------------------------------------------------------------------------------------------------------------------------------------

-- 한 회원에 대한 할인쿠폰 조회
SELECT E.NAME, E.SALE
FROM EVENT_BOX B, EVENT E
WHERE B.IS_EVENT = 'n' AND B.ID = 'dong' AND B.EVENT_CODE = E.EVENT_CODE;


SELECT E.NAME, E.SALE FROM EVENT_BOX B, EVENT E WHERE B.IS_EVENT = 'n' AND B.ID = 'dong' AND B.EVENT_CODE = E.EVENT_CODE;
SELECT * FROM CAR WHERE CAR_NO = '11하0123';

INSERT INTO RENT(ID, CAR_NO, INS_CODE, RENT_DATE, RETURN_DATE, IS_RENT, RENT_FARE, RENT_REMARK) 
values('dong', '11하0123', 1, to_date('2020-10-30','YYYY-MM-DD HH24:MI:SS'), 
to_date('2020-10-27','YYYY-MM-DD HH24:MI:SS'), 'y', 80000, '동동 렌트 테스트');

SELECT * FROM KIND;

SELECT * FROM INSURANCE
ORDER BY INS_CODE;

SELECT * FROM OPTIONS;
SELECT * FROM OPTIONS ORDER BY OPT_CODE;

SELECT min(return_date) FROM RENT WHERE CAR_NO = '11하0123';
